export const RouteEnum = {
  HOME: "/",
  // DASHBOARD: "/",
  LOGIN: "/login",
  SIGNUP: "/complete-signUp",
  DASHBOARD: "/dashboard",
  SIGNUPCLIENT: "/signup-client",
  MANAGE_COMPANIES:"/manage-companies",
  MANAGE_RIDERS:"/manage-riders",
  TRIPS:"/trips",
  MAPS:"/maps",
  SUPPORT:"/support",
  LIST_OF_MEDICINES:"/list-of-medicines",
  MEDICINE_GROUPS:"/medicine-groups",
};
